# Generated by Django 6.1 on 2026-08-19 16:45

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='productvariant',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='orderitem',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='store.productvariant'),
        ),
        migrations.AddField(
            model_name='product',
            name='variant_type',
            field=models.CharField(blank=True, choices=[('', 'Aucune variante'), ('Taille', 'Taille'), ('Pointure', 'Pointure'), ('Couleur', 'Couleur'), ('Autre', 'Autre')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='option_name',
            field=models.CharField(blank=True, editable=False, max_length=100),
        ),
        migrations.AddConstraint(
            model_name='productvariant',
            constraint=models.UniqueConstraint(fields=('product', 'option_name', 'option_value'), name='unique_product_variant'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='store.product'),
        ),
    ]
